/**
 * 
 * This class file is for handling custom exception generated by Trigo Functions.
 * 
 * @author ASE Group 6
 * Dhrumil shah 	( 110024036 )
 * Raj Patel 		( 110020706 )
 * Sunny Patel 		( 110010345 )
 * Yash Patel 		( 110011738 )
 * 
 * @version 1.0.0
 * 
 */

package group6.taylortrigo;

public class TrigoException extends Exception
{
	public TrigoException(String s)
	{
		super(s);
	}
}
